# Generated by Django 6.0.1 on 2026-02-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='courses',
            field=models.ManyToManyField(blank=True, to='Pathway.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pathway.district'),
        ),
    ]
