# Generated by Django 6.0.1 on 2026-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathway', '0002_course_instructor_district_courses_student_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptentry',
            name='gradeTaken',
            field=models.IntegerField(choices=[(9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gradeLevel',
            field=models.IntegerField(choices=[(9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')]),
        ),
        migrations.AlterField(
            model_name='transcriptentry',
            name='grade',
            field=models.IntegerField(help_text='Final numeric grade (0–100)'),
        ),
    ]
