# Generated by Django 6.0.1 on 2026-02-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathway', '0003_transcriptentry_gradetaken_alter_student_gradelevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='transcripts')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pathway.student')),
            ],
        ),
    ]
