# Generated by Django 6.0.1 on 2026-02-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathway', '0004_transcriptupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isCoreClass',
            field=models.BooleanField(default=False, help_text='Mark True when this class is required for district graduation.'),
        ),
    ]
