# Generated by Django 6.0.1 on 2026-02-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathway', '0005_course_iscoreclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='isCoreClass',
            field=models.BooleanField(help_text='Set by district course setup to mark classes required for graduation.'),
        ),
    ]
